spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
